### ISSUE TITLE
Cross-platform support

### ISSUE THREAD

**Issue by ghost** [haampie/libtree#29]
Cross-platform support is very useful in a cross-compilation environment. [ncopa/lddtree](https://github.com/ncopa/lddtree) has this feature.

**Comment by haampie** [comment]
Thanks for opening the issue, do you have an example where libtree doesn't work at the moment? In principle libtree should just parse generic ELF files, but I'm not 100% sure it handles search paths correctly.

**Comment by tianyuanhao** [comment]
I found that you use environment variables to set the search path, which is not intuitive enough. And `libtree` wrapper needs to be placed in the target root directory.

Some shared libraries are located in subdirectories of `lib`, which you have not considered. For example, `libsystemd-shared-246.so` located under `lib/systemd`.

```
systemctl
└── libsystemd-shared-246.so not found
```

**Comment by haampie** [comment]
Do you mean you want to have an argument to set the filesystem root elsewhere? Is `[new root]/etc/ld.so.conf` expected to exist when cross-compiling?

> I found that you use environment variables to set the search path

https://man7.org/linux/man-pages/man8/ld.so.8.html is followed, so LD_LIBRARY_PATH is considered. Can you tell me a bit more on what you would expect when cross-compiling?

> Some shared libraries are located in subdirectories of lib, which you have not considered. For example, libsystemd-shared-246.so located under lib/systemd.

Can you be a bit more precise? What OS are you on? Is this still related to cross-compiling?

**Comment by tianyuanhao** [comment]
Yes, it is related to cross compilation. I have no problem using it in the native environment.

The cross compilation environment I use is Buildroot.

**Comment by haampie** [comment]
Thanks, that makes it a bit easier to test it.
