### ISSUE TITLE
Readme example not working

### ISSUE THREAD

**Issue by okaerin** [haampie/libtree#30]
The example deployment of libtree itself does not work, if it is installed and invoked as stated there. This is due to the fact, that the libtree command is a shell and not a elf binary (at least in the github release). I suggest that this is updated or shown with a different example.

**Comment by haampie** [comment]
Thanks, weird how that went unnoticed!

**Comment by haampie** [comment]
Maybe it's better to just drop the wrapper for `strip` and `patchelf` and check on startup if it is in the PATH, cause right now a very specific version of these binaries is forced upon the user.

**Comment by haampie** [comment]
Version 2.0.0 now ships a static executable for `libtree`, and has a tarball with static `libtree`, `strip` and `patchelf`.
