### ISSUE TITLE
Add arm64 exclusions

### ISSUE THREAD

**Issue by rossburton** [haampie/libtree#62]
If you're going to skip the x86-64 `ld-linux` then you might like to know what the aarch64 libraries are called:
```
$ libtree /bin/echo -p
/bin/echo
└── /lib/aarch64-linux-gnu/ld-linux-aarch64.so.1 [ld.so.conf]
```

**Comment by haampie** [comment]
Right, also POWER has ld64.so and alpine linux x86_64: `libc.musl-x86_64.so.1`. Feel free to create a pull request targeting master
