### ISSUE TITLE
libtree, the name

### ISSUE THREAD

**Issue by alexmyczko** [haampie/libtree#68]
Thanks for this software, it's nice. However, wouldn't you want to rename it to lddtree?
libletter names are usually for library software.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1004927

**Comment by haampie** [comment]
Hi Alex, thanks for taking this on :) `lddtree` is also an executable with similar functionality provided by pax-utils.

`libtree` appears as `libtree-ldd` in some distro's, see e.g. https://repology.org/project/libtree-ldd/versions, which I think is a fine name as well.

**Comment by alexmyczko** [comment]
oh and it's almost doing the same too:

```
root@sid:/# libtree /usr/bin/upx
/usr/bin/upx 
├── libz.so.1 [ld.so.conf]
└── libucl.so.1 [ld.so.conf]
root@sid:/# lddtree /usr/bin/upx
upx => /usr/bin/upx (interpreter => /lib64/ld-linux-x86-64.so.2)
    libucl.so.1 => /usr/lib/x86_64-linux-gnu/libucl.so.1
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
        ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by haampie** [comment]
Yeah, but lddtree is quite slow

```
$ time lddtree /usr/bin/* > /dev/null
real	3m12.000s

$ time libtree -v /usr/bin/* > /dev/null
real	0m0.169s
```

**Comment by alexmyczko** [comment]
a lot faster if you have 6500+ binaries in /usr/bin, lddtree aborted after 18', libtree be done in 0.5"

**Comment by alexmyczko** [comment]
should appear shortly at https://buildd.debian.org/status/package.php?p=libtree&suite=sid

**Comment by alexmyczko** [comment]
https://repology.org/project/libtree-ldd/versions
