### ISSUE TITLE
Shipping chrpath and strip

### ISSUE THREAD

**Issue by haampie** [haampie/libtree#9]
Currently `chrpath` and `strip` are shipped in the releases and added to the path via a shell script. But when building from source and running `make install` there's no guarantee `chrpath` and `strip` are available (and they will fail silently if not).

Maybe it's best to just remove `chrpath` and `strip` from the release and make the user install them. A warning could be added when `--strip`, `--chrpath` and `-d` are set but the tools are not available.

**Comment by otreblan** [comment]
> Currently `chrpath` and `strip` are shipped in the releases and added to the path via a shell script. But when building from source and running `make install` there's no guarantee `chrpath` and `strip` are available (and they will fail silently if not).
> 
> Maybe it's best to just remove `chrpath` and `strip` from the release and make the user install them. A warning could be added when `--strip`, `--chrpath` and `-d` are set but the tools are not available.

Added `binutils` and `chrpath` to the dependency list: https://aur.archlinux.org/packages/libtree/
