### ISSUE TITLE
FEAT: Reverse dependencies

### ISSUE THREAD

**Issue by lee-b** [haampie/libtree#90]
It would be really nice to be able to give this a library and have it scan the system for files which use that library, and then see the dependency tree in a similar way.  For example, to use the screenshot on the github repo page as an example, if I gave it libogg.so.0, it should show libogg.so.0 at the top, then vim as one of the executables that use it, and then libogg.so.0 underneath as shown in the screenshot, perhaps in that sort of separate coloring, to show that this was the library in question, within that dep tree.  OR, perhaps it could show libogg.so at the top, libvorbisfile below that, and at the bottom, vim.

**Comment by haampie** [comment]
Reverse dependency information is not available, it requires a scan of all executables on the system, which doesn't sound great.
